containers:
- name: backend
  image: 381492221394.dkr.ecr.us-east-1.amazonaws.com/backend:latest
  ports:
  - containerPort: 3000
  env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: host
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: dbname
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
