apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  host: database-1.cluster-cd48uaq4c2vd.us-east-1.rds.amazonaws.com
  dbname: database-1
  username: postgres
  password: Ank150402ita
